=== alekcm/ES2/ExampleHero/Documentation/Schemas/IndustryConstructibleElement.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="IndustryConstructibleElement" nillable="true" type="IndustryConstructibleElement" />
  <xs:complexType name="IndustryConstructibleElement">
    <xs:complexContent mixed="false">
      <xs:extension base="ConstructibleElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="NextUpgradeName" type="xs:string" />
        </xs:sequence>
        <xs:attribute default="false" name="IsUnique" type="xs:boolean" />
        <xs:attribute default="false" name="BuiltOnce" type="xs:boolean" />
        <xs:attribute default="false" name="OncePerWorld" type="xs:boolean" />
        <xs:attribute default="false" name="IsRefundable" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ConstructibleElement">
    <xs:complexContent mixed="false">
      <xs:extension base="UnlockDatatableElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="AIGain" type="AIGain" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SupervisorGain" type="SupervisorGain" />
          <xs:element minOccurs="0" maxOccurs="1" default="0" name="BuyoutCostModifier" type="xs:float" />
          <xs:element minOccurs="0" maxOccurs="1" name="Tags" type="Tags" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="InProgressSimulationDescriptorReference" type="SimulationDescriptorReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="QueuedSimulationDescriptorReference" type="SimulationDescriptorReference" />
          <xs:element minOccurs="0" maxOccurs="1" name="ConstructionQueueEntityActionReference" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="CostReductionReference" type="CostReductionReference" />
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="InfiniteCost" type="InfiniteCost" />
            <xs:element minOccurs="0" maxOccurs="1" name="CustomCost" type="CustomConstructionCost" />
            <xs:element minOccurs="0" maxOccurs="1" name="Cost" type="ConstructionCost" />
          </xs:choice>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="SupportPrerequisite" type="SupportPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="TechnologyPrerequisite" type="TechnologyPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
          </xs:choice>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="MetaPrerequisite" type="MetaPrerequisite" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="PopulationEvent" type="XmlNamedReference" />
        </xs:sequence>
        <xs:attribute default="false" name="Stackable" type="xs:boolean" />
        <xs:attribute name="Category" type="xs:string" />
        <xs:attribute name="SubCategory" type="xs:string" />
        <xs:attribute name="ScoreProvider" type="xs:string" />
        <xs:attribute default="false" name="Hidden" type="xs:boolean" />
        <xs:attribute default="false" name="ConsumeResourceSurplus" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="AIGain">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Tag" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="RessourceName" type="xs:string" />
    <xs:attribute default="false" name="Inverted" type="xs:boolean" />
  </xs:complexType>
  <xs:complexType name="SupervisorGain">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Tags" type="Tags" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute default="1" name="Weight" type="xs:float" />
  </xs:complexType>
  <xs:complexType name="Tags">
    <xs:simpleContent>
      <xs:extension base="xs:string" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SimulationDescriptorReference">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValueType" />
  <xs:complexType name="XmlNamedReference">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="CostReductionReference">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="InfiniteCost">
    <xs:attribute name="ResourceName" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="CustomConstructionCost">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Instant" type="xs:boolean" />
        <xs:attribute default="false" name="InstantOnCompletion" type="xs:boolean" />
        <xs:attribute name="ResourceName" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ConstructionCost">
    <xs:simpleContent>
      <xs:extension base="xs:float">
        <xs:attribute default="false" name="Instant" type="xs:boolean" />
        <xs:attribute default="false" name="InstantOnCompletion" type="xs:boolean" />
        <xs:attribute name="ResourceName" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SupportPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite">
        <xs:attribute name="Politics" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathValidityPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TechnologyPrerequisite">
    <xs:simpleContent>
      <xs:extension base="PathValidityPrerequisite">
        <xs:attribute default="false" name="UnlockHidden" type="xs:boolean" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InterpreterPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="MetaPrerequisite">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="SupportPrerequisite" type="SupportPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="TechnologyPrerequisite" type="TechnologyPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="Operator" type="PrerequisiteOperator" use="required" />
  </xs:complexType>
  <xs:simpleType name="PrerequisiteOperator">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Or" />
      <xs:enumeration value="And" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="UnlockDatatableElement">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:element name="StarSystemImprovementDefinition" nillable="true" type="StarSystemImprovementDefinition" />
  <xs:complexType name="StarSystemImprovementDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="IndustryConstructibleElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="UniqueTags" type="Tags" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="EncounterGlobalEffectDescriptorReference" type="SimulationDescriptorReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="EncounterEntityReference" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="1" name="StarSystemDescriptors" type="ArrayOfSimulationDescriptorReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="TemporaryEffect" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfSimulationDescriptorReference">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="PlanetImprovementDefinition" nillable="true" type="PlanetImprovementDefinition" />
  <xs:complexType name="PlanetImprovementDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="IndustryConstructibleElement" />
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="PlanetTerraformationDefinition" nillable="true" type="PlanetTerraformationDefinition" />
  <xs:complexType name="PlanetTerraformationDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="IndustryConstructibleElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="RemovedType" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="PlanetActionImprovementDefinition" nillable="true" type="PlanetActionImprovementDefinition" />
  <xs:complexType name="PlanetActionImprovementDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="PlanetImprovementDefinition">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="EntityActionDefinitionReference" type="XmlNamedReference" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="StarSystemResourceImprovementDefinition" nillable="true" type="StarSystemResourceImprovementDefinition" />
  <xs:complexType name="StarSystemResourceImprovementDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="StarSystemImprovementDefinition">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="Resource" type="ResourceProviderDefinition" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ResourceProviderDefinition">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:element name="StarSystemDecolonizeImprovementDefinition" nillable="true" type="StarSystemDecolonizeImprovementDefinition" />
  <xs:complexType name="StarSystemDecolonizeImprovementDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="StarSystemImprovementDefinition">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="EntityActionDefinitionReference" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="Resource" type="ResourceProviderDefinition" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="PlanetColonizationConstructibleElement" nillable="true" type="PlanetColonizationConstructibleElement" />
  <xs:complexType name="PlanetColonizationConstructibleElement">
    <xs:complexContent mixed="false">
      <xs:extension base="IndustryConstructibleElement">
        <xs:attribute name="PlanetType" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="StarSystemPopulationTransformImprovementDefinition" nillable="true" type="StarSystemPopulationTransformImprovementDefinition" />
  <xs:complexType name="StarSystemPopulationTransformImprovementDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="StarSystemImprovementDefinition">
        <xs:attribute name="PopulationSource" type="xs:string" />
        <xs:attribute default="LowestCount" name="PopulationSourceHeuristic" type="PopulationChangeHeuristic" />
        <xs:attribute name="PopulationDestination" type="xs:string" />
        <xs:attribute default="LowestCount" name="PopulationDestinationHeuristic" type="PopulationChangeHeuristic" />
        <xs:attribute default="1" name="PopulationToTransformCount" type="xs:int" />
        <xs:attribute default="false" name="CreateIfNotAvailable" type="xs:boolean" />
        <xs:attribute default="false" name="IgnoreInvinciblePopulation" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="PopulationChangeHeuristic">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LowestCount" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="TradeCompanyHeadquartersStarSystemImprovementDefinition" nillable="true" type="TradeCompanyHeadquartersStarSystemImprovementDefinition" />
  <xs:complexType name="TradeCompanyHeadquartersStarSystemImprovementDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="StarSystemImprovementDefinition" />
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="TradeCompanySubsidiaryStarSystemImprovementDefinition" nillable="true" type="TradeCompanySubsidiaryStarSystemImprovementDefinition" />
  <xs:complexType name="TradeCompanySubsidiaryStarSystemImprovementDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="StarSystemImprovementDefinition" />
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="StarSystemTimeBubbleImprovementDefinition" nillable="true" type="StarSystemTimeBubbleImprovementDefinition" />
  <xs:complexType name="StarSystemTimeBubbleImprovementDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="StarSystemImprovementDefinition">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="TimeBubbleDefinition" type="XmlNamedReference" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== alekcm/ES2/Dustborns_V9/Simulation/ConstructibleElement_Industry[StarSystemImprovement].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/IndustryConstructibleElement.xsd">
    <!-- Покупка Пылерождённого за пыль -->
    <StarSystemPopulationTransformImprovementDefinition Name="StarSystemImprovementCreateMajorPopulationDustborns" SubCategory="SubCategoryPopulation" ScoreProvider="StarSystemImprovementBuilt"
                                                      PopulationDestination="Major" PopulationToTransformCount="1" CreateIfNotAvailable="true" ConsumeResourceSurplus="true">
        <AIGain RessourceName="PopulationGain" Inverted="false"></AIGain>
        <SupervisorGain Name="Dust" Weight="0.5"/>
        <Tags>NoBuyout</Tags>
        <QueuedSimulationDescriptorReference Name="QueuedDescriptorIncreaseVirtualPopulationDustborns"/>
        <CustomCost ResourceName="EmpireMoney" Instant="true">250 * Property(StockLocation, @../ClassEmpire, GameSpeedMultiplier, true)</CustomCost>
        <PathPrerequisite Inverted="false" Flags="Prerequisite,Discard">ClassColonizedStarSystem</PathPrerequisite>
        <PathPrerequisite Inverted="false" Flags="Prerequisite,Discard">../ClassEmpire/PopulationMajor,ClassPopulationEmpireAffinityDustborns</PathPrerequisite>
        <InterpreterPrerequisite Flags="MaximumPopulationSystem,Enqueue">(Property(Context,@ClassColonizedStarSystem, MaximumPopulation) ge (1 + Property(Context,@ClassColonizedStarSystem, Population) + Property(Context,@ClassColonizedStarSystem, VirtualPopulation)))</InterpreterPrerequisite>
        <InterpreterPrerequisite Flags="Prerequisite">(Property(Context,@ClassColonizedStarSystem, MaximumPopulation) ge (Property(Context,@ClassColonizedStarSystem, Population) + Property(Context,@ClassColonizedStarSystem, VirtualPopulation)))</InterpreterPrerequisite>
        <SimulationDescriptorReference Name="StarSystemImprovementCreateMajorPopulationDustborns"/>
    </StarSystemPopulationTransformImprovementDefinition>

    <!-- Распыление Пылерождённого -->
    <StarSystemPopulationTransformImprovementDefinition Name="StarSystemImprovementSellMajorPopulationDustborns" SubCategory="SubCategoryPopulation" ScoreProvider="StarSystemImprovementBuilt"
                                                      PopulationSource="AffinityDustborns" IgnoreInvinciblePopulation="true">
        <AIGain RessourceName="PopulationGain" Inverted="true"></AIGain>
        <SupervisorGain Name="Dust" Weight="0.5"/>
        <Tags>NoBuyout</Tags>
        <Cost ResourceName="SystemTurnBased">1</Cost>
        <PathPrerequisite Inverted="false" Flags="Prerequisite">ClassColonizedStarSystem/ClassPopulationStarSystemAffinityDustborns</PathPrerequisite>
        <PathPrerequisite Inverted="false" Flags="Prerequisite,Discard">../ClassEmpire/PopulationMajor,ClassPopulationEmpireAffinityDustborns</PathPrerequisite>
        <InterpreterPrerequisite Flags="Prerequisite">Property(Context,@'ClassColonizedStarSystem/ClassPopulationStarSystemAffinityDustborns', PopulationCount) ge 1</InterpreterPrerequisite>
        <SimulationDescriptorReference Name="StarSystemImprovementSellMajorPopulationDustborns"/>
        <!-- Возврат 250 пыли. Основной путь - TemporaryEffect (как у переваривания, там работает). -->
        <TemporaryEffect>DustbornSellDustReward</TemporaryEffect>
        <!-- ЗАПАСНОЙ ВАРИАНТ, если TemporaryEffect всё равно не платит: закомментируй строку выше и раскомментируй строку ниже.
        <CustomCost ResourceName="EmpireMoney" Instant="true">-250 * Property(StockLocation, @../ClassEmpire, GameSpeedMultiplier, true)</CustomCost>
        -->
    </StarSystemPopulationTransformImprovementDefinition>

    <!-- Покупка Безвольных за пыль удалена: Безвольные получаются ТОЛЬКО переработкой чужого населения -->

    <!-- Бесплатная постройка "Сконструировать Безвольного" (Home) также удалена -->

    <!-- Конверсия минора в Безвольного +300 пыли, требует Пылерождённого.
         Паттерн взят из ванильной постройки Хоратио "Clone Major Population"
         (StarSystemPopulationTransformImprovementDefinition PopulationSource="Minor"
         PopulationDestination="Major"): корректные пути к минорной популяции -
         ColonizedStarSystemStateColony/ClassColonizedPlanet/PopulationNonMajor. -->
    <StarSystemPopulationTransformImprovementDefinition Name="StarSystemImprovementConvertToBezvolny" SubCategory="SubCategoryPopulation" ScoreProvider="StarSystemImprovementBuilt"
                                                      PopulationSource="Minor" PopulationSourceHeuristic="LowestCount"
                                                      PopulationDestination="Major" PopulationDestinationHeuristic="LowestCount"
                                                      PopulationToTransformCount="1">
        <AIGain RessourceName="PopulationGain" Inverted="false"></AIGain>
        <SupervisorGain Name="Industry" Weight="0.5"/>
        <Tags>NoBuyout</Tags>
        <Cost ResourceName="SystemTurnBased">1</Cost>
        <!-- В системе есть Пылерождённые -->
        <PathPrerequisite Inverted="false" Flags="Prerequisite,Discard">ClassColonizedStarSystem/ClassPopulationStarSystemAffinityDustborns</PathPrerequisite>
        <!-- На планете колонии есть не-мажорная (минорная) популяция -->
        <PathPrerequisite Inverted="false" Flags="Prerequisite,Disable">ColonizedStarSystemStateColony/ClassColonizedPlanet/PopulationNonMajor</PathPrerequisite>
        <!-- Есть кого переваривать: население системы > мажорного -->
        <InterpreterPrerequisite Inverted="false" Flags="NotEnoughPopulation,Enqueue">(Property(Context, @ClassColonizedStarSystem, Population) - Property(Context, @ClassColonizedStarSystem, MajorPopulationCount)) gt 0</InterpreterPrerequisite>
        <SimulationDescriptorReference Name="StarSystemImprovementConvertToBezvolny"/>
        <TemporaryEffect>BezvolnyDustReward</TemporaryEffect>
    </StarSystemPopulationTransformImprovementDefinition>

    <!-- ============ 2.10 ПЕРЕРАБОТКА В СЧИТАЮЩУЮ ОБОЛОЧКУ ============
         Альтернатива обычной переработке: пыль НЕ даётся, вместо Безвольного - Считающая Оболочка.
         Доступна только после разблокировки квестом (флаг EmpireUnlockedScholarShells). -->
    <StarSystemPopulationTransformImprovementDefinition Name="StarSystemImprovementConvertToScholar" SubCategory="SubCategoryPopulation" ScoreProvider="StarSystemImprovementBuilt"
                                                      PopulationSource="Minor" PopulationSourceHeuristic="LowestCount"
                                                      PopulationDestination="Major" PopulationToTransformCount="1" CreateIfNotAvailable="true" ConsumeResourceSurplus="true">
        <AIGain RessourceName="PopulationGain" Inverted="false"></AIGain>
        <SupervisorGain Name="Science" Weight="0.5"/>
        <Tags>NoBuyout</Tags>
        <Cost ResourceName="SystemTurnBased">1</Cost>
        <PathPrerequisite Inverted="false" Flags="Prerequisite,Discard">ClassColonizedStarSystem/ClassPopulationStarSystemAffinityDustborns</PathPrerequisite>
        <PathPrerequisite Inverted="false" Flags="Prerequisite,Discard">ClassColonizedStarSystem/PopulationMinor</PathPrerequisite>
        <PathPrerequisite Inverted="false" Flags="Prerequisite,Discard">../ClassEmpire,EmpireUnlockedScholarShells</PathPrerequisite>
        <SimulationDescriptorReference Name="StarSystemImprovementConvertToScholar"/>
    </StarSystemPopulationTransformImprovementDefinition>

    <!-- ============ 4-B АБРАЗИВНЫЙ СТАН ============
         Требует истощённую планету в системе. Даёт +10% силы армии, пока стоит. -->
    <StarSystemImprovementDefinition Name="StarSystemImprovementAbrasiveForge" SubCategory="SubCategoryEmpire" ScoreProvider="StarSystemImprovementBuilt">
        <SupervisorGain Name="Industry" Weight="0.5"/>
        <UniqueTags>AbrasiveForge</UniqueTags>
        <CustomCost ResourceName="SystemProduction">400 * Property(StockLocation, @../ClassEmpire, GameSpeedMultiplier, true)</CustomCost>
        <PathPrerequisite Inverted="false" Flags="Prerequisite,Discard">../ClassEmpire,DustbornRewardAbrasiveForge</PathPrerequisite>
        <PathPrerequisite Inverted="false" Flags="Prerequisite">ClassColonizedStarSystem/ClassColonizedPlanet,PlanetDepletionMalus</PathPrerequisite>
        <SimulationDescriptorReference Name="StarSystemImprovementAbrasiveForge"/>
    </StarSystemImprovementDefinition>

    <!-- ============ 5-A КУРГАН ОСЕВШИХ ============
         +4 производства ЛЮБОМУ населению на истощённых планетах этой системы. -->
    <StarSystemImprovementDefinition Name="StarSystemImprovementSettledBarrow" SubCategory="SubCategoryEmpire" ScoreProvider="StarSystemImprovementBuilt">
        <SupervisorGain Name="Industry" Weight="0.7"/>
        <UniqueTags>SettledBarrow</UniqueTags>
        <CustomCost ResourceName="SystemProduction">300 * Property(StockLocation, @../ClassEmpire, GameSpeedMultiplier, true)</CustomCost>
        <PathPrerequisite Inverted="false" Flags="Prerequisite,Discard">../ClassEmpire,DustbornRewardSettledBarrow</PathPrerequisite>
        <PathPrerequisite Inverted="false" Flags="Prerequisite">ClassColonizedStarSystem/ClassColonizedPlanet,PlanetDepletionMalus</PathPrerequisite>
        <SimulationDescriptorReference Name="StarSystemImprovementSettledBarrow"/>
    </StarSystemImprovementDefinition>

</Datatable>
